name: release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  test:
    runs-on: ubuntu-20.04
    container: iamdey/lmn-3-daw-docker-compiler:amd64
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target Tests -j8
      - name: run unit tests
        run: |
          ./build/Tests/Tests_artefacts/Release/Tests

  build_x86_64:
    runs-on: ubuntu-20.04
    container: iamdey/lmn-3-daw-docker-compiler:amd64

    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fuse-ld=lld
          cmake --build build -j8
          zip -r -j LMN-3-x86_64.zip ./build/LMN-3_artefacts/Release/LMN-3 ./LICENSE


      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LMN-3-x86_64
          path: LMN-3-x86_64.zip
          retention-days: 1

  build_arm:
    runs-on: ubuntu-20.04
    container: iamdey/lmn-3-daw-docker-compiler:armv7

    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: patch
        run: |
          (cd tracktion_engine && patch -i ../patches_armv7/BufferedFileReader.patch -p1)
          (cd tracktion_engine/modules/juce && patch -i ../../../patches_armv7/juce_dsp.h.patch -p1)
          (cd tracktion_engine && patch -i ../patches_armv7/crill-21.patch -p1)
          (cd tracktion_engine && patch -i ../patches_armv7/progressive_backoff_wait.h.patch -p1)
          (cd tracktion_engine && patch -i ../patches_armv7/tracktion_CPU.patch -p1)
          (cd tracktion_engine && patch -i ../patches_armv7/tracktion_NodePlayerUtilities.patch -p1)

      # -DPACKAGE_TESTS=OFF so that the tests dont get executed once build is finished
      - name: build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPACKAGE_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=/toolchain/toolchain.cmake
          cmake --build build -j8
          zip -r -j LMN-3-arm-linux-gnueabihf.zip ./build/LMN-3_artefacts/Release/LMN-3 ./LICENSE

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LMN-3-arm-linux-gnueabihf
          path: LMN-3-arm-linux-gnueabihf.zip
          retention-days: 1

  build_aarch64:
    runs-on: ubuntu-20.04
    container: iamdey/lmn-3-daw-docker-compiler:arm64

    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # -DPACKAGE_TESTS=OFF so that the tests dont get executed once build is finished
      - name: build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DPACKAGE_TESTS=OFF -DCMAKE_TOOLCHAIN_FILE=/toolchain/toolchain.cmake
          cmake --build build -j8
          zip -r -j LMN-3-aarch64-linux-gnu.zip ./build/LMN-3_artefacts/Release/LMN-3 ./LICENSE

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LMN-3-aarch64-linux-gnu
          path: LMN-3-aarch64-linux-gnu.zip
          retention-days: 1

  release:
    runs-on: ubuntu-20.04
    needs: [build_x86_64, build_arm, build_aarch64]
    steps:
      - name: Download x86-64 LMN-3 artifact
        uses: actions/download-artifact@v3
        with:
          name: LMN-3-x86_64
      - name: Download arm-linux-gnueabihf LMN-3 artifact
        uses: actions/download-artifact@v3
        with:
          name: LMN-3-arm-linux-gnueabihf
      - name: Download aarch64-linux-gnu LMN-3 artifact
        uses: actions/download-artifact@v3
        with:
          name: LMN-3-aarch64-linux-gnu
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            LMN-3-x86_64.zip
            LMN-3-arm-linux-gnueabihf.zip
            LMN-3-aarch64-linux-gnu.zip
